block for allocation task
dh-center/QueSt pull request #107
Opened 2021-06-28 19:25 UTC by Panda0412

2021-06-28 19:35 UTC, ilyamore88 commented on src/components/questBlocks/AllocationDropDown.tsx
> +    }
Выглядит очень странно. Switch-case для boolean

2021-06-28 19:35 UTC, ilyamore88 commented on src/components/questBlocks/AllocationDropDown.tsx
> +    // transform: [ { translateY: 50% } ],
Закомментированный код

2021-06-28 19:35 UTC, ilyamore88 commented on src/components/questBlocks/AllocationTask.tsx
> +    .sort(() => Math.random() - 0.5);
Что за магическое число

2021-06-28 21:56 UTC, Panda0412 commented on src/components/questBlocks/AllocationDropDown.tsx
> +    }
Там ещё undefined с отдельным поведением

2021-06-28 21:57 UTC, Panda0412 commented on src/components/questBlocks/AllocationTask.tsx
> +    .sort(() => Math.random() - 0.5);
Сортировка в рандомном порядке
Чтобы варианты ответов перемешать

2021-06-29 04:25 UTC, nikmel2803 requested changes

2021-06-29 04:25 UTC, nikmel2803 commented on src/contexts/AudioAccompanimentContext.tsx
> +          setIsPlaying(!isPlaying);
зачем это

2021-06-29 04:25 UTC, nikmel2803 commented on src/components/questBlocks/AllocationTask.tsx
> +              userAnswersCorrectness[index] = answer === props.data.data.options[index].left;
1) тут больше forEach подходит
2) нельзя так записывать в state

2021-06-29 04:25 UTC, nikmel2803 commented on src/components/questBlocks/AllocationTask.tsx
> +          if (userAnswers.filter(answer => answer !== undefined).length !== props.data.data.options.length) {
вынеси условие в отдельную переменную, чтобы проще читалось

2021-06-29 04:25 UTC, nikmel2803 commented on src/components/questBlocks/AllocationTask.tsx
> +    .sort(() => Math.random() - 0.5);
можно вынести это в функцию randomSort, чтобы понятнее было

2021-06-29 09:26 UTC, Panda0412 commented on src/contexts/AudioAccompanimentContext.tsx
> +          setIsPlaying(!isPlaying);
Чтобв послушать повторно

2021-06-29 10:58 UTC, Panda0412 commented on src/components/questBlocks/AllocationTask.tsx
> +              userAnswersCorrectness[index] = answer === props.data.data.options[index].left;
а как можно?

2021-06-29 11:48 UTC, nikmel2803 approved these changes

2021-06-29 11:50 UTC, ilyamore88 approved these changes

2021-06-29 11:51 UTC, merged