Design for completed quests
dh-center/QueSt pull request #11
Opened 2020-09-28 15:26 UTC by Panda0412

2020-09-28 17:46 UTC, ilyamore88 requested changes
![image](https://user-images.githubusercontent.com/37909603/94467363-7fdb4f00-01cb-11eb-9b13-dc37cf1e2fb2.png)
- ~~Скролбар наезжает на список~~
- Было бы классно добавить сверху и снизу размытые границы или тени, которые будут заходить на список

2020-09-28 18:00 UTC, ilyamore88 requested changes
- ~~У кнопок нет border.~~
- ~~Текст внешне отличается от шаблона. Кажется, шрифты не подключены.~~
- ~~Заголовок Квесты не отцентрован.~~

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
> +  button: {
Давай дадим какое-то более осознанное название классу. Например, `questItem`

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
> +            <Image source={require('../images/done.png')} style={{
Её же можно в svg экспортировать из фигмы. Это же векторная графика.

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
> +    backgroundColor: 'rgba(64, 190, 32, 0.5)',
Где-то задаём цвета в rgd, где-то в rgba. Мб можно все цвета задавать через #?

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
> +            <Text numberOfLines={2} style={styles.questName}>
![image](https://user-images.githubusercontent.com/37909603/94468304-de54fd00-01cc-11eb-847e-b7b71e15f3be.png)
По дизайну, может быть и три строки.

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
>   */
А что за доки-то такие прекрасные?

2020-09-28 18:00 UTC, ilyamore88 commented on src/components/Quests.tsx
> +          <TouchableOpacity style={styles.button}>
При коротком клике никакого эффекта не наблюдаю. Только при зажатии кнопки.

2020-09-28 18:56 UTC, Panda0412 commented on src/components/Quests.tsx
> +          <TouchableOpacity style={styles.button}>
На короткий клик будет реакция, если установить onPress

2020-09-28 19:04 UTC, ilyamore88 commented on src/components/Quests.tsx
> +          <TouchableOpacity style={styles.button}>
Тогда не очень понимаю, зачем вообще использовать этот компонент, если честно. Но вообще, реакцию на клики должна Лидия отрисовать.

2020-09-29 09:22 UTC, ilyamore88 requested changes
- Зачем векторную графику экспортировать в png - всё ещё не понятно для меня.
- У кнопки назад в QuestInfo маленькая зона нажатия. Не с первого раза попадаю. Вот как в дизайне например: 
![image](https://user-images.githubusercontent.com/37909603/94539820-67f8df00-024e-11eb-9f89-cd8917116c21.png)

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    // box-shadow: 0px 1px 2px rgba(33, 68, 104, 0.4);
🤨

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    // box-shadow: 1px 1px 3px rgba(0, 46, 66, 0.5);
🤨

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    // box-shadow: 1px 1px 3px rgba(0, 46, 66, 0.5);
🤨

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    color: 'rgba(0,0,0,0.8)',
Странно, что линтер не ставит пробелы после ,

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    >;
Доков нет. 
Надеюсь, линтер ты запускала, и это уже его косяк с такими отступами.

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/AppNavigator.tsx
> + *
🤨

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/AppNavigator.tsx
> +export type QuestsStackParamList = {
Хотелось бы доки 👉👈

2020-09-29 09:22 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +          <Image source={require('../images/footprint.png')} style={{ marginRight: 5 }}/>
У иконок дописала одинаковые madgin. Почему бы в класс не вынести?

2020-09-30 08:46 UTC, ilyamore88 requested changes
![image](https://user-images.githubusercontent.com/37909603/94663611-87f1d680-0312-11eb-8759-b1e099c726c9.png)
![image](https://user-images.githubusercontent.com/37909603/94663622-8c1df400-0312-11eb-9aed-814b3b797522.png)

2020-09-30 08:46 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +  },
🤨

2020-09-30 12:23 UTC, nikmel2803 requested changes

2020-09-30 12:23 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +    height: '100%',
они точно нужны? 
кажется, я их убирал и ничего не менялось

2020-09-30 12:23 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +          justifyContent: 'space-around',
надо убрать инлайн стили

2020-09-30 12:23 UTC, nikmel2803 commented on android/app/build.gradle
> +        multiDexEnabled true
для чего изменения в этом файле? можно ссылку на доки?

2020-09-30 12:42 UTC, Panda0412 commented on src/components/QuestInfo.tsx
> +    height: '100%',
Да, нужны

2020-09-30 12:47 UTC, Panda0412 commented on android/app/build.gradle
> +        multiDexEnabled true
https://developer.android.com/studio/build/multidex

2020-10-04 08:43 UTC, ilyamore88 reviewed
В принципе всё ок, комменты чисто на будущее, как можно сократить немного кода в стилях. А ты минифицировала картинки?

2020-10-04 08:43 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    paddingLeft: 41,
Такие паддинги можно в одну строчку записывать как `padding: 0 41,`. Первое - отступы сверху и снизу, второе - отступы по бокам.

2020-10-04 08:43 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    paddingBottom: 15,
И тут можно написать `padding: 15 16 15 0,`.

2020-10-04 08:43 UTC, ilyamore88 commented on src/components/Quests.tsx
> +    paddingLeft: 60,
А вот тут вообще прекрасно сокращается до одной строки `padding: 15 60,`.

2020-10-05 14:43 UTC, Panda0412 commented on src/components/QuestInfo.tsx
> +    paddingLeft: 41,
В React Native так не работает :с
Я и так, и сяк скормить пыталась

2020-10-05 15:16 UTC, nikmel2803 approved these changes

2020-10-05 16:06 UTC, ilyamore88 approved these changes

2020-10-05 16:26 UTC, merged