implemented profile screen
dh-center/QueSt pull request #12
Opened 2020-09-30 16:19 UTC by Panda0412

2020-09-30 18:25 UTC, ilyamore88 requested changes
- В горизонтальном режиме нет скролла.
- В дизайне названия кнопок с маленькой, хз как лучше, может быть это была задумка дизайнера?

2020-09-30 18:25 UTC, ilyamore88 commented on src/components/Profile.tsx
> +    // borderColor: 'rgba(0, 0, 0, 0.8)',
Бан?

2020-10-02 11:32 UTC, Panda0412 commented on src/components/Profile.tsx
> +    // borderColor: 'rgba(0, 0, 0, 0.8)',
Я не нашла ничего пунтого про бордер вокруг буковок :с

2020-10-03 22:53 UTC, nikmel2803 commented on src/components/Profile.tsx
> + * Functional component of the person's page
```suggestion
 * Displays user's profile
```

2020-10-03 23:04 UTC, nikmel2803 commented on src/components/Profile.tsx
> +    marginRight: -2,
Убрать странные маржины

2020-10-03 23:04 UTC, nikmel2803 commented on src/components/Profile.tsx
> +  fill: {
назвать понятнее

2020-10-03 23:04 UTC, nikmel2803 commented on src/components/Profile.tsx
> +  settings: {
```suggestion
  settingsButton: {
```

2020-10-03 23:04 UTC, nikmel2803 commented on src/components/Profile.tsx
> +  info: {
```suggestion
  userInfo: {
```

2020-10-03 23:04 UTC, nikmel2803 commented on src/components/Profile.tsx
> +  login: {
```suggestion
  caption: {
```

2020-10-04 08:35 UTC, ilyamore88 approved these changes
Только Никитины комменты пофикси.

2020-10-05 15:42 UTC, nikmel2803 approved these changes

2020-10-05 16:05 UTC, ilyamore88 approved these changes

2020-10-05 16:59 UTC, merged