Quest info new design
dh-center/QueSt pull request #23
Opened 2020-12-02 19:05 UTC by Panda0412

2020-12-02 21:17 UTC, ilyamore88 reviewed
Фото заменить на jpg/png

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    backgroundColor: Colors.WHITE,
```suggestion
    backgroundColor: Colors.BACKGROUND,
```

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    backgroundColor: Colors.BACKGROUND,
Не обязательно

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    color: Colors.BLACK,
Почему для этого не используются стили текста

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +            <Text style={styles.descriptionTitleText}>Достижения</Text>
Нет локализации

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +    color: Colors.BLACK,
Опять же, стили текста

2020-12-02 21:17 UTC, ilyamore88 commented on src/components/QuestInfo.tsx
> +  cardText: {
И тут стили текста

2020-12-02 21:18 UTC, ilyamore88 commented
Разнести по компонентам QuestInfo

2020-12-02 21:26 UTC, nikmel2803 requested changes

2020-12-02 21:26 UTC, nikmel2803 commented on src/App.tsx
> +          <StatusBar backgroundColor="rgba(255, 255, 255, 0)" barStyle="dark-content" translucent={true}/>
надо поставить transparent

2020-12-02 21:26 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +      <View style={styles.container}>
ненужная вложенность

2020-12-02 21:26 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +              </View>
Нужно вынести в отдельный компонент

2020-12-02 21:26 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +            <View style={styles.cardView} />
что это за пустой блок?

2020-12-02 21:26 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +            </TouchableOpacity>
У нас есть компонент с кнопкой
Туда надо только нужный стиль прокидывать (цвет)

2020-12-02 21:26 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +                  width={Dimensions.get('screen').width * 0.448}
- магический цифры
- проблема (какая?) не должна так решаться

2020-12-05 15:23 UTC, nikmel2803 requested changes

2020-12-05 15:23 UTC, nikmel2803 commented on src/components/Achievement.tsx
> + * @param Props
- с маленькой буквы
- описание

2020-12-05 15:23 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +            </View>
так и не вынесено в компонент

2020-12-05 15:23 UTC, nikmel2803 commented on src/components/QuestInfo.tsx
> +          })}/>
давай тут каждый проп на новой строчке сделаем

2020-12-05 18:09 UTC, nikmel2803 approved these changes

2020-12-05 18:52 UTC, ilyamore88 approved these changes

2020-12-06 01:49 UTC, merged