Profile redesign
dh-center/QueSt pull request #29
Opened 2020-12-09 02:59 UTC by Panda0412

2020-12-09 07:51 UTC, ilyamore88 requested changes

2020-12-09 07:51 UTC, ilyamore88 commented on src/images/achievements.svg
> +<path d="M7.475 10.35C8.42769 10.35 9.2 9.57769 9.2 8.625C9.2 7.67231 8.42769 6.9 7.475 6.9C6.52231 6.9 5.75 7.67231 5.75 8.625C5.75 9.57769 6.52231 10.35 7.475 10.35Z" fill="#55556B"/>
Возможно, лучше использовать currentColor в fill, чтобы управлять цветом через css

2020-12-09 07:51 UTC, ilyamore88 commented on src/navigation/profileStack.tsx
> +      {/* }*/}
При мерже не забыть раскомментировать

2020-12-09 07:51 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +// shadowRadius: 2.62;
Закомментированный код

2020-12-09 07:51 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +  elevation: ${4};
А просто `'4'` не работает?

2020-12-09 07:51 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +        </Button>
Можно вынести в отдельный компонент `ButtonWithIcon`. Передавать иконку в пропы.

2020-12-09 07:51 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +const Body = styled.SafeAreaView`
Кажется тут flex не хватает. Но потом можно будет заменить на мою обёртку, когда этот реквест смержим.

2020-12-09 07:51 UTC, ilyamore88 commented on src/screens/Profile.tsx
> + * Type with props of screen 'Main' in QuestsStackScreen
Неправильный док

2020-12-09 12:19 UTC, Panda0412 commented on src/screens/Profile.tsx
> +// shadowRadius: 2.62;
Это тень для iOS, она тут для Никиты, потому что мы не уверены, что box-shadow будет работать

> Закомментированный код

2020-12-09 12:19 UTC, Panda0412 commented on src/screens/Profile.tsx
> +  elevation: ${4};
> А просто `'4'` не работает?

Работает, но подсвечивается как ошибка

2020-12-09 12:22 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +  elevation: ${4};
А что за ошибка?

2020-12-09 12:24 UTC, Panda0412 commented on src/screens/Profile.tsx
> +  elevation: ${4};
![image](https://user-images.githubusercontent.com/44259704/101629529-8e977b00-3a32-11eb-9a88-0546ffd52aea.png)

2020-12-09 12:25 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +  elevation: ${4};
Хех, понятно. А одним box-shadow не обойтись? Просто где-то его вроде как хватило.

2020-12-09 12:26 UTC, Panda0412 commented on src/screens/Profile.tsx
> +  elevation: ${4};
На андроиде он не работает
Он тут прописан в надежде на то, что сработает в ios

2020-12-09 12:27 UTC, ilyamore88 commented on src/screens/Profile.tsx
> +  elevation: ${4};
Ох уж этот Android...

2020-12-09 12:30 UTC, Panda0412 commented on src/images/achievements.svg
> +<path d="M7.475 10.35C8.42769 10.35 9.2 9.57769 9.2 8.625C9.2 7.67231 8.42769 6.9 7.475 6.9C6.52231 6.9 5.75 7.67231 5.75 8.625C5.75 9.57769 6.52231 10.35 7.475 10.35Z" fill="#55556B"/>
> Возможно, лучше использовать currentColor в fill, чтобы управлять цветом через css

Вроде так не будет работать, но я попробую

2020-12-10 16:15 UTC, ilyamore88 commented on src/components/ProfileButton.tsx
> +  icon: JSX.Element;
Лучше ReactNode кажется

2020-12-10 16:25 UTC, ilyamore88 requested changes

2020-12-10 16:25 UTC, ilyamore88 commented on src/components/ProfileButton.tsx
> +      <Icon>{icon}</Icon>
И зачем такая обёртка, нельзя передать стили прямо в icon?

2020-12-10 16:25 UTC, ilyamore88 commented on src/images/achievements.svg
> +<path d="M7.475 10.35C8.42769 10.35 9.2 9.57769 9.2 8.625C9.2 7.67231 8.42769 6.9 7.475 6.9C6.52231 6.9 5.75 7.67231 5.75 8.625C5.75 9.57769 6.52231 10.35 7.475 10.35Z" fill="#55556B"/>
А почему это собственно не должно работать? У меня в svg в реквесте с навигацией сработало.

2020-12-10 16:25 UTC, ilyamore88 commented on src/images/blueEllipse.svg
> +<ellipse opacity="0.15" cx="358.5" cy="240" rx="358.5" ry="240" fill="#68C6DF"/>
А что здесь с размерами произошло? Разве не через css их менять надо, если такое требуется?

2020-12-10 16:25 UTC, ilyamore88 commented on src/styles/textStyles.ts
> +};
Почему здесь только font-family? Можно же сделать прямо как в стилях для StyleSheet сразу с несколькими стилями в одной переменной (размер, цвет и т.д.)

2020-12-10 16:29 UTC, Panda0412 commented on src/styles/textStyles.ts
> +};
Я хотела, но Никита сказал только фонты прописать

2020-12-10 16:30 UTC, Panda0412 commented on src/images/blueEllipse.svg
> +<ellipse opacity="0.15" cx="358.5" cy="240" rx="358.5" ry="240" fill="#68C6DF"/>
У меня эллипс неправильно скачан был, это просто другая свг

2020-12-10 16:31 UTC, Panda0412 commented on src/components/ProfileButton.tsx
> +      <Icon>{icon}</Icon>
Попробую

2020-12-10 16:32 UTC, Panda0412 commented on src/images/achievements.svg
> +<path d="M7.475 10.35C8.42769 10.35 9.2 9.57769 9.2 8.625C9.2 7.67231 8.42769 6.9 7.475 6.9C6.52231 6.9 5.75 7.67231 5.75 8.625C5.75 9.57769 6.52231 10.35 7.475 10.35Z" fill="#55556B"/>
Покажи как, я перепробовала кучу всего

2020-12-10 16:33 UTC, ilyamore88 commented on src/images/achievements.svg
> +<path d="M7.475 10.35C8.42769 10.35 9.2 9.57769 9.2 8.625C9.2 7.67231 8.42769 6.9 7.475 6.9C6.52231 6.9 5.75 7.67231 5.75 8.625C5.75 9.57769 6.52231 10.35 7.475 10.35Z" fill="#55556B"/>
Посмотри тут #27.

2020-12-12 16:36 UTC, ilyamore88 commented on src/components/ProgressBlock.tsx
> +export interface ProgressProps {
Тогда можно сразу и level передавать

2020-12-12 16:51 UTC, nikmel2803 approved these changes

2020-12-12 16:53 UTC, ilyamore88 approved these changes

2020-12-12 17:03 UTC, merged