QuestsLists redesign
dh-center/QueSt pull request #31
Opened 2020-12-13 23:23 UTC by Panda0412

2020-12-14 11:46 UTC, ilyamore88 requested changes
Лоадер при загрузке квестов не по центру экрана

2020-12-14 11:46 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +export interface ButtonProps {
```suggestion
export interface ItemProps {
```

2020-12-14 11:46 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
У тебя же border-radius есть у родителя

2020-12-14 11:46 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +
```suggestion
```

2020-12-14 12:59 UTC, Panda0412 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Есть
А тут если не написать, то они перекроются прямыми углами

2020-12-14 12:59 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Overflow: hidden?

2020-12-14 13:00 UTC, Panda0412 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Тогда на ios не будет видно теней

2020-12-14 13:03 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
![image](https://user-images.githubusercontent.com/37909603/102084185-d6991200-3e25-11eb-905d-1c740b4d94c3.png)
facebook сказал resolved 🗿

2020-12-14 13:05 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Ну вообще, просто странно так делать

2020-12-14 13:46 UTC, Panda0412 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
> ![image](https://user-images.githubusercontent.com/37909603/102084185-d6991200-3e25-11eb-905d-1c740b4d94c3.png)
> facebook сказал resolved 🗿

А как?)

2020-12-14 13:55 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Да они там шизы

2020-12-14 13:57 UTC, Panda0412 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Ну то есть никак
Да?

2020-12-14 13:57 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Да

2020-12-14 14:02 UTC, Panda0412 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Ну, Resolve получается

2020-12-14 14:03 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +  border-bottom-left-radius: 15px;
Кажется да :(

2020-12-18 00:09 UTC, nikmel2803 commented on src/screens/QuestsList.tsx
> +          setIsLoading(true);
поставь тут `@todo`, что надо чтобы setLoading(false) вызывался уже после того, как все данные загрузились
а то забыть можем

2020-12-18 00:09 UTC, nikmel2803 commented on src/screens/QuestsList.tsx
> +              <Title>Квест не найден</Title>
`К сожалению, произошла ошибка 😢.  Пожалуйста, попробуйте повторить запрос спустя некоторое время.`

2020-12-18 00:09 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +    top: -376,
а это зачем?

2020-12-18 00:28 UTC, Panda0412 commented on src/screens/QuestInfo.tsx
> +    top: -376,
Чтобы кружочек всегда на одном уровне был
А то так получалось, что при названии квеста в 2 строки он ниже, чем при однострочном названии, потому что был позиционирован относительно низа header.

2020-12-18 00:31 UTC, Panda0412 commented on src/screens/QuestsList.tsx
> +              <Title>Квест не найден</Title>
Квестов нет, но вы держитесь :3

2020-12-18 00:31 UTC, nikmel2803 commented on src/screens/QuestsList.tsx
> +              <Title>Квест не найден</Title>
их не нет
ты проверяешь наличие ошибки
если их, не в props будет пустой массив квестов

2020-12-18 01:18 UTC, nikmel2803 commented on src/screens/QuestsList.tsx
> +              <Error>
Error — это встроенный констуктор ошибки
лучше переименовать в ErrorText

2020-12-18 01:20 UTC, nikmel2803 approved these changes

2020-12-18 08:56 UTC, ilyamore88 approved these changes

2020-12-18 11:15 UTC, merged