Add image to Test
dh-center/QueSt pull request #32
Opened 2020-12-14 01:45 UTC by Panda0412

2020-12-14 11:39 UTC, nikmel2803 requested changes

2020-12-14 11:39 UTC, nikmel2803 commented on src/components/TestView.tsx
> +}
А документация где?

2020-12-14 11:49 UTC, ilyamore88 requested changes

2020-12-14 11:49 UTC, ilyamore88 commented on src/components/TestView.tsx
> +  }
Можно добавить тут комментарии?

2020-12-14 11:49 UTC, ilyamore88 commented on src/components/TestView.tsx
> +      </Modal>
Что будет, если фото нет? Modal у тебя создаётся в любом случае.

2020-12-14 14:39 UTC, Panda0412 commented on src/components/TestView.tsx
> +      </Modal>
visible никогда не станет true
могу добавить проверку, но надо ли?

2020-12-14 14:44 UTC, ilyamore88 commented on src/components/TestView.tsx
> +      </Modal>
Понимаю, но ты создаёшь Image с uri: undefined

2020-12-14 14:44 UTC, ilyamore88 commented on src/components/TestView.tsx
> +      </Modal>
Это не приведёт к ошибке?

2020-12-14 14:44 UTC, ilyamore88 commented on src/components/TestView.tsx
> +      </Modal>
Да и зачем нагружать вёрстку этими блоками, если картинки нет.

2020-12-14 15:56 UTC, ilyamore88 requested changes

2020-12-14 15:56 UTC, ilyamore88 commented on src/components/TestView.tsx
> +          {(selectedAnswer !== undefined) && <TouchableOpacity><Next style={styles.next}/></TouchableOpacity>}
А можно тут переносы сделать для читаемости плз?

2020-12-14 15:56 UTC, ilyamore88 commented on src/components/TestView.tsx
> +    // Image component, if testQuestion has picture uri
Сделай их многострочными с `/**`

2020-12-14 16:20 UTC, ilyamore88 approved these changes

2020-12-18 00:15 UTC, nikmel2803 approved these changes

2020-12-18 00:22 UTC, merged