Question
dh-center/QueSt pull request #37
Opened 2020-12-21 23:43 UTC by Panda0412

2020-12-24 11:29 UTC, ilyamore88 requested changes

2020-12-24 11:29 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +  const [isAnswered, setIsAnswered] = useState<boolean>();
Из названия следует, что переменная false, если пользователь не ответил. У тебя же, суда по коду, тут false при неправильном ответе.

2020-12-24 11:29 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +          placeholder={'Введите ответ'}
Мы не переводим эти блоки?

2020-12-24 11:29 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +          </TouchableOpacity>
Эта кнопка, кажется, тоже становится отдельным компонентом

2020-12-24 11:29 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +}
А этот интерфейс где-то используется? Просто пропы у компонента пустые.

2020-12-24 12:40 UTC, Panda0412 commented on src/components/QuestionView.tsx
> +          placeholder={'Введите ответ'}
А вот я не знаю
Квест же на русском чисто, поэтому мне показалось, что нет необходимости переводить внутри квеста

2020-12-24 12:41 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +          placeholder={'Введите ответ'}
Я тоже как раз поэтому и спросил

2020-12-24 12:42 UTC, ilyamore88 commented on src/components/QuestionView.tsx
> +          placeholder={'Введите ответ'}
Ну вообще, наверно интерфейс лучше везде переводить. Локализация квестов зависит от api и админки. А не от приложения.

2020-12-24 12:43 UTC, Panda0412 commented on src/components/QuestionView.tsx
> +          placeholder={'Введите ответ'}
Ну ок, не сложно как бы

2020-12-30 01:54 UTC, nikmel2803 commented on src/components/QuestWalkthroughRenderer.tsx
> +        break;
проще просто написать 
```
      case 'test':
      case 'question':
          break;
```

2020-12-30 01:54 UTC, nikmel2803 commented on src/components/questBlocks/QuestionView.tsx
> +  min-height: 100%;
flex: 1?

2020-12-30 01:54 UTC, nikmel2803 commented on src/components/questBlocks/TestView.tsx
> +    shadowRadius: 2.62,
зачем вслепую менять тени на другой ОС?

2020-12-30 02:47 UTC, Panda0412 commented on src/components/questBlocks/TestView.tsx
> +    shadowRadius: 2.62,
Вообще не вслепую
У нас уже есть такой elevation, с проверенным аналогом под ios

2020-12-30 02:48 UTC, Panda0412 commented on src/components/questBlocks/QuestionView.tsx
> +  min-height: 100%;
Скажи все параметры обёртки в твоём решении плез

2020-12-30 09:38 UTC, nikmel2803 approved these changes

2020-12-30 09:40 UTC, ilyamore88 approved these changes

2020-12-30 09:43 UTC, merged