Add user location
dh-center/QueSt pull request #41
Opened 2020-12-27 01:23 UTC by Panda0412

2020-12-27 01:40 UTC, nikmel2803 commented on src/screens/Map.tsx
> +    task().then();
надо добавить обработчик catch и сделай там алерт о том, что не удалось получить права для определения геопозиции

2020-12-28 11:01 UTC, nikmel2803 requested changes

2020-12-28 11:01 UTC, nikmel2803 commented on src/components/MapView.tsx
> +    task().then();
мне кажется нет особого смысла делать отдельную функцию для этого
давай это уберём, оставим тут 
```ts
requestLocationPermission()
  .then(per => setPermission(per))
  .catch(() => Alert.alert('Не удалось получить вашу локацию для отображения'))
```

Надо не забыть про перевод алерта

2020-12-28 11:01 UTC, nikmel2803 commented on src/components/MapView.tsx
> +    task().then();
Даже прям не requestLocationPermission(), а сразу MapboxGL.requestAndroidLocationPermissions, тут не вижу смысла в обёртке

2020-12-28 11:49 UTC, Panda0412 commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
Зачем? Оно же работает корректно и без этого

2020-12-28 11:51 UTC, nikmel2803 commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
точно не знаю, но во всех туториалах оно есть
давай оставим, хуже не будет
может быть для того, чтобы при установке пользователь видел, какие нужны разрешения приложению

2020-12-28 13:38 UTC, nikmel2803 commented on src/components/MapView.tsx
> +  const [permission, setPermission] = useState(false);
напоследок
давай назовём лучше `hasPermission`

2020-12-28 13:43 UTC, nikmel2803 approved these changes

2020-12-28 13:56 UTC, ilyamore88 approved these changes

2020-12-28 13:57 UTC, merged