Blocks rendering
dh-center/QueSt pull request #42
Opened 2020-12-27 22:40 UTC by Panda0412

2020-12-28 11:09 UTC, nikmel2803 requested changes

2020-12-28 11:09 UTC, nikmel2803 commented on src/components/QuestWalkthroughRenderer.tsx
> +    shadowRadius: 4.65,
это без проблем в styled задаётся
и надо уже это вынести в отдельный компонент

2020-12-28 11:09 UTC, nikmel2803 commented on src/components/QuestWalkthroughRenderer.tsx
> +        }
давай у нас эта кнопка будет в самих компонентах теста
будем в TestView прокидывать обработчик, который он вызовет когда пользователь прошёл квест и ему надо двигаться дальше

2020-12-28 11:09 UTC, nikmel2803 commented on src/components/questBlocks/Text.tsx
> +    shadowOffset: {
ну не пиши ты так стили

2020-12-28 11:53 UTC, Panda0412 commented on src/components/questBlocks/Text.tsx
> +    shadowOffset: {
А как через styled сделать, чтоб потом прокидывать чисто название типа для нужного стиля?

2020-12-29 09:41 UTC, nikmel2803 reviewed
очень классно выглядит 👍

2020-12-29 09:41 UTC, nikmel2803 commented on src/components/questBlocks/QuestTextBlock.tsx
> +import React from 'react';
А чего ты файл переименовала?
Просто папка и так называется QuestBlocks, так что зачем у файла это дублировать. Пусть он просто называется Text (будет `questBlocks/Text`), а компонент надо оставить с полным именем

2020-12-29 09:41 UTC, nikmel2803 commented on src/components/questBlocks/QuestTextBlock.tsx
> +  nextFunction: () => void;
давай лучше `nextCallback`. Callback общепринятое название

2020-12-29 09:58 UTC, ilyamore88 requested changes

2020-12-29 09:58 UTC, ilyamore88 commented on src/components/questBlocks/QuestTextBlock.tsx
> +              </>;
А вот это всё не лучше вынести в отдельный компонент Quote?

2020-12-29 09:58 UTC, ilyamore88 commented on src/types/questData.ts
> +    caption: string;
Док

2020-12-29 09:58 UTC, ilyamore88 commented on src/components/ui/NextButton.tsx
> + * Custom button with light blue background
Док не соответствует назначению этой кнопки

2020-12-29 15:49 UTC, Panda0412 commented on src/components/questBlocks/QuestTextBlock.tsx
> +import React from 'react';
Может хоть TextBlock? А то просто Text путает

2020-12-29 15:49 UTC, nikmel2803 commented on src/components/questBlocks/QuestTextBlock.tsx
> +import React from 'react';
ну ок

2020-12-29 19:49 UTC, ilyamore88 commented on src/components/questBlocks/TextBlock.tsx
> +export default function QuestTextBlock(props: QuestTextBlockProps): React.ReactElement {
Не соответствует названию файла

2020-12-29 21:13 UTC, ilyamore88 approved these changes

2020-12-29 21:15 UTC, nikmel2803 approved these changes

2020-12-29 21:15 UTC, merged