add required minimum level to blocked quests from api
dh-center/QueSt pull request #55
Opened 2021-02-09 01:08 UTC by Panda0412

2021-02-09 14:08 UTC, nikmel2803 commented on src/components/QuestsListItem.tsx
> +        {progressState === 'LOCKED' && <AvailableCondition>Достигните {minLevel} уровня</AvailableCondition>}
нет перевода

2021-02-10 17:26 UTC, ilyamore88 requested changes
Почему для локализации не использовать `useTranslation` хук? И что в файле переводов делает `<Text></Text>`?

2021-02-10 19:28 UTC, ilyamore88 requested changes

2021-02-10 19:28 UTC, ilyamore88 commented on src/components/QuestsListItem.tsx
> +        {progressState === 'LOCKED' && <AvailableCondition>{t('quests.condition', { minLevel: minLevel })}</AvailableCondition>}
```suggestion
        {progressState === 'LOCKED' && <AvailableCondition>{t('quests.condition', { minLevel })}</AvailableCondition>}
```

2021-02-10 19:31 UTC, ilyamore88 approved these changes

2021-02-11 08:48 UTC, nikmel2803 approved these changes

2021-02-11 09:02 UTC, merged