QuestInfo redesign
dh-center/QueSt pull request #68
Opened 2021-03-31 13:12 UTC by Panda0412

2021-04-12 12:26 UTC, nikmel2803 requested changes
— кнопка начала квеста начала перекрываться
— bottom sheet почти полностью скрыт за таббаром. Кто-то сломал подсчёт высоты таббара

2021-04-12 12:26 UTC, nikmel2803 commented on src/locales/ru/translation.json
> +    "achievements_passed": "Прогресс в достижениях",
почему snake_case

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +  width: ${props => props.vertical ? 1 : Dimensions.get('screen').width - 30}px;
почему не поставить просто margin 15 по бокам?

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +    creditsImage = route.params.credits.find(item => item.type === 'image').data.file.url;
ban

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +        </BackButton>
давай это вынесем в отдельный компонент

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +          <Gradient
Давай этот градиент тоже как-то отдельно вынесем, больно много места занимает

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +                    Квест создан в соавторстве с {<CreditsText>{decodeHTMLEntities(creditsInfo)}</CreditsText>}
этот текст будет в админке заноситься, здесь не нужно

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +          <Info tabBarHeight={tabBarHeight}>
1) предлагаю вынести этот компонент тоже
2) зачем tabBarHeight?
3) по идее нужно сделать это фрагментом через relay

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +          <Info tabBarHeight={tabBarHeight}>
по хорошему, QuestInfo тоже должен быть фрагментом.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/32655339/114393981-59976280-9ba3-11eb-9493-d85bc852039d.png">
и вот так дублировать типы ты не должна

2021-04-12 12:26 UTC, nikmel2803 commented on src/screens/QuestInfo.tsx
> +          <Info tabBarHeight={tabBarHeight}>
надо почитать как адекватно использовать relay вместе react navigation

2021-04-28 06:22 UTC, nikmel2803 commented on src/components/utils/useTabBarHeight.ts
> +  const TAB_BAR_OWM_HEIGHT = 78;
OWN

2021-04-28 12:49 UTC, nikmel2803 approved these changes

2021-04-28 12:49 UTC, nikmel2803 approved these changes

2021-04-28 13:03 UTC, ilyamore88 approved these changes

2021-04-28 15:26 UTC, merged