Watching for user position during the quest
dh-center/QueSt pull request #74
Opened 2021-05-22 21:24 UTC by Panda0412

2021-05-22 21:30 UTC, nikmel2803 commented on src/contexts/TargetLocationContext.tsx
> +    }
стоит в cleanup тоже делать clearWatch, мне кажется
https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup

2021-05-22 21:30 UTC, nikmel2803 commented on src/components/MapView.tsx
> +  const bottomOffset = useTabBarHeight() - insets.bottom + (props.children ? 50 :  10);
это для чего всё?

2021-05-22 21:32 UTC, Panda0412 commented on src/components/MapView.tsx
> +  const bottomOffset = useTabBarHeight() - insets.bottom + (props.children ? 50 :  10);
<img width="50" alt="Снимок экрана 2021-05-23 в 00 32 44" src="https://user-images.githubusercontent.com/44259704/119241352-6625b800-bb5e-11eb-8853-815dcbab9c39.png">
Для этой фигни

2021-05-24 14:08 UTC, nikmel2803 commented on src/components/questBlocks/LocationInstance.tsx
> +        <CustomMarker style={{ transform: [ { translateY: -21.5 } ] }}/>
это что за магическое число такое

2021-05-24 14:08 UTC, nikmel2803 commented on src/components/MapView.tsx
> +        y: Platform.OS === 'ios' ? 20 : insets.top + 20 }}
а у андроида что будет в insets.top? не 0?

2021-05-24 14:10 UTC, Panda0412 commented on src/components/questBlocks/LocationInstance.tsx
> +        <CustomMarker style={{ transform: [ { translateY: -21.5 } ] }}/>
Из фигмы посчитала
Там нам нужно не совсем на 50% сместить из-за тени

2021-05-24 14:13 UTC, nikmel2803 commented on src/components/questBlocks/LocationInstance.tsx
> +        <CustomMarker style={{ transform: [ { translateY: -21.5 } ] }}/>
1) какой тени, не вижу в фигме её
2) разве тень должна как-то влиять на положение маркера?
3) надо вынеси магическое число в переменную

2021-05-24 14:14 UTC, nikmel2803 commented on src/components/MapView.tsx
> +        y: Platform.OS === 'ios' ? 20 : insets.top + 20 }}
не очень понятна цель такого ветвления

2021-05-24 14:17 UTC, Panda0412 commented on src/components/questBlocks/LocationInstance.tsx
> +        <CustomMarker style={{ transform: [ { translateY: -21.5 } ] }}/>
1. 
<img width="249" alt="Снимок экрана 2021-05-24 в 17 16 00" src="https://user-images.githubusercontent.com/44259704/119360849-b95d4f00-bcb3-11eb-8600-3c226564faec.png">
2. Да, смещение идёт так, чтобы совпадали именно кончики маркера, а размер svg идёт с тенью

2021-05-24 14:18 UTC, Panda0412 commented on src/components/MapView.tsx
> +        y: Platform.OS === 'ios' ? 20 : insets.top + 20 }}
В ios верхний инсет учитывается из коробки

2021-05-26 06:51 UTC, nikmel2803 commented on src/components/questBlocks/LocationInstance.tsx
> +        <CustomMarker style={{ transform: [ { translateY: -21.5 } ] }}/>
надо вынести и немного описать для чего это надо, примерно как ты тут сделала

2021-05-26 06:51 UTC, nikmel2803 commented on src/components/MapView.tsx
> +        y: Platform.OS === 'ios' ? 20 : insets.top + 20 }}
вынеси это плз тоже в константу и задокументируй, чтобы не было вопросов почему

2021-05-26 07:44 UTC, nikmel2803 requested changes
- надо пофисить предыдущие комменты
- маркер локации кажется слишком большим (особенно по сравнению с маркером пользователя)
- у меня не билдится без следующих изменений:

```
Index: ios/Podfile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/ios/Podfile b/ios/Podfile
--- a/ios/Podfile	(revision dbafe4c21c3cff4b37ccdb5f0357755d5e3e57c3)
+++ b/ios/Podfile	(date 1622013710416)
@@ -19,7 +19,7 @@
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
-  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
+#   use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
   post_install do |installer|
     flipper_post_install(installer)
     installer.pods_project.build_configurations.each do |config|
Index: ios/QueSt/AppDelegate.m
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/ios/QueSt/AppDelegate.m b/ios/QueSt/AppDelegate.m
--- a/ios/QueSt/AppDelegate.m	(revision dbafe4c21c3cff4b37ccdb5f0357755d5e3e57c3)
+++ b/ios/QueSt/AppDelegate.m	(date 1622014410812)
@@ -10,6 +10,8 @@
 #import <React/RCTBridge.h>
 #import <React/RCTBundleURLProvider.h>
 #import <React/RCTRootView.h>
+#import <FBSDKCoreKit/FBSDKCoreKit.h>
+#import <RNGoogleSignin/RNGoogleSignin.h>
 
 #ifdef FB_SONARKIT_ENABLED
 #import <FlipperKit/FlipperClient.h>
@@ -18,8 +20,7 @@
 #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
 #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
 #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
-#import <FBSDKCoreKit/FBSDKCoreKit.h>
-#import <RNGoogleSignin/RNGoogleSignin.h>
+
 
 static void InitializeFlipper(UIApplication *application) {
   FlipperClient *client = [FlipperClient sharedClient];

```

2021-05-27 05:43 UTC, nikmel2803 approved these changes

2021-05-27 10:28 UTC, merged