switch tabs
dh-center/QueSt pull request #80
Opened 2021-06-02 14:32 UTC by Panda0412

2021-06-02 15:41 UTC, nikmel2803 approved these changes

2021-06-02 15:41 UTC, nikmel2803 commented on src/screens/Achievements.tsx
> +  const [currentTab, setCurrentTab] = useState(1);
давай enum вместо голых цифр

2021-06-02 15:41 UTC, nikmel2803 commented on src/screens/Achievements.tsx
> +          paddingHorizontal: 15,
<img width="563" alt="image" src="https://user-images.githubusercontent.com/32655339/120509260-05557580-c3d1-11eb-8e1f-cc33d17e9d74.png">

2021-06-02 15:41 UTC, nikmel2803 commented on src/screens/Achievements.tsx
> +              : achievementsList.filter(achievement => achievement.progress < 100)
<img width="544" alt="image" src="https://user-images.githubusercontent.com/32655339/120509320-143c2800-c3d1-11eb-97bb-3a49e6aa65e4.png">

2021-06-02 15:42 UTC, nikmel2803 requested changes
мисклик

2021-06-03 11:53 UTC, nikmel2803 commented on src/screens/Achievements.tsx
> +  }
надо вынеси из тела компонента
и доки
и название лучше не просто Tabs и например AchievementsScreenTabs

2021-06-03 12:16 UTC, nikmel2803 approved these changes

2021-06-03 13:14 UTC, ilyamore88 approved these changes

2021-06-10 07:51 UTC, merged