Reset password
dh-center/QueSt pull request #95
Opened 2021-06-17 17:57 UTC by Panda0412

2021-06-17 18:29 UTC, nikmel2803 requested changes

2021-06-17 18:29 UTC, nikmel2803 commented on src/components/BlueTextButton.tsx
> +}
нет доков
названия булевых пропов не по стандарту
да и вообще, точно ли они нужны?

2021-06-17 18:29 UTC, nikmel2803 commented on src/components/TextualBackButton.tsx
> +`;
да сколько блять можно

2021-06-17 18:29 UTC, nikmel2803 commented on src/components/TextualBackButton.tsx
> + * @param props - props for button
нету описания компонента

2021-06-17 18:29 UTC, nikmel2803 commented on src/screens/ResetPassword.tsx
> +    case 1:
1) почему не сделать нормальный переход между экранами? зачем эти костыли со стейтом и условиями
2) что за магические цифры? Надо юзать enum

2021-06-17 18:29 UTC, nikmel2803 commented on src/screens/ResetPassword.tsx
> +        commitMutation(
если мы начали юзать новое API, давай и мутации по новому тоже писать чтоль

2021-06-18 13:10 UTC, nikmel2803 commented on src/components/BlueTextButton.tsx
> + * @param props - props for button
нет описания
что и для чего оно
почему именно blue

2021-06-18 13:10 UTC, nikmel2803 commented on src/screens/InputCode.tsx
> +          commitMutation(
давай юзать новое API для мутаций

2021-06-18 13:10 UTC, nikmel2803 commented on src/screens/InputCode.tsx
> +        onPress={() => navigation.navigate('SetNewPassword', { email: route.params.email,
давай проверим, что если пользователь ввёл меньше 6 символов, то покажем Алерт о том что он дурак

2021-06-18 13:11 UTC, Panda0412 commented on src/screens/InputCode.tsx
> +        onPress={() => navigation.navigate('SetNewPassword', { email: route.params.email,
Я думала об этом
Если больше, в целом-то тоже дурак

2021-06-18 13:12 UTC, nikmel2803 commented on src/screens/InputCode.tsx
> +        onPress={() => navigation.navigate('SetNewPassword', { email: route.params.email,
да.

2021-06-18 13:14 UTC, Panda0412 commented on src/screens/InputCode.tsx
> +        onPress={() => navigation.navigate('SetNewPassword', { email: route.params.email,
Я сделаю, но всё ещё надеюсь на проверку кода через апи на этом этапе

2021-06-18 13:14 UTC, Panda0412 commented on src/screens/InputCode.tsx
> +        onPress={() => navigation.navigate('SetNewPassword', { email: route.params.email,
В будущем

2021-06-18 15:17 UTC, nikmel2803 approved these changes

2021-06-18 15:42 UTC, ilyamore88 approved these changes

2021-06-18 15:42 UTC, merged